package com.jiubredeemer.auth.exception

enum class ErrorCode {
    PASSWORD_DO_NOT_MATCH,
    MISSED_REQUIRED_FIELD,
    OTHER,
    USER_EXISTS_BY_EMAIL,
    USER_NOT_FOUND_BY_EMAIL,
    USER_EXISTS_BY_USERNAME,
    INVALID_PASSWORD,
    EXPIRED_JWT,
    VERIFICATION_CODE_INVALID,
    VERIFICATION_CODE_COOLDOWN,
    VERIFICATION_CODE_EXPIRED,
}
